"""m2m relation update 2

Revision ID: 4ee97bd6083c
Revises: 86a0653a5107
Create Date: 2018-03-27 20:11:42.400028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee97bd6083c'
down_revision = '86a0653a5107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'categories', ['cat_id'], ['cat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'cat_id')
    # ### end Alembic commands ###
