"""m2m relation update

Revision ID: 86a0653a5107
Revises: 4c9036849f7b
Create Date: 2018-03-27 20:08:54.189884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86a0653a5107'
down_revision = '4c9036849f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('last_cat_update', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('categories', 'last_update')
    op.add_column('users', sa.Column('last_urs_update', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'is_locked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_sysadmin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'temporary_pwd',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('users', 'last_emp_update')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_emp_update', mysql.DATETIME(), nullable=True))
    op.alter_column('users', 'temporary_pwd',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_sysadmin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_locked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('users', 'last_urs_update')
    op.add_column('categories', sa.Column('last_update', mysql.DATETIME(), nullable=True))
    op.drop_column('categories', 'last_cat_update')
    # ### end Alembic commands ###
