"""m2m relation update 3

Revision ID: 92c2111bf9b4
Revises: 4ee97bd6083c
Create Date: 2018-03-27 21:41:41.015775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92c2111bf9b4'
down_revision = '4ee97bd6083c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'cat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cat_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'categories', ['cat_id'], ['cat_id'])
    # ### end Alembic commands ###
